# Checkov Configuration

# Framework and directory settings
framework:
  - terraform

# Directories to scan
directory:
  - '.'

# Output format options
output:
  - cli
  - json
  - sarif

# Output file for results
output-file-path: 'checkov-results'

# Compact mode for cleaner output
compact: true

# Quiet mode (reduce verbosity)
quiet: false

# Download external modules for scanning
download-external-modules: true

# External modules directory
external-modules-download-path: '.external_modules'

# Custom policies directory
external-checks-dir:
  - 'checkov-policies/'

# Soft fail mode (don't exit with error code)
soft-fail: false

# Hard fail on specific severities
hard-fail-on:
  - CRITICAL
  - HIGH

# Enable secret scanning
enable-secret-scan-all-files: true

# Repository metadata
repo-id: 'image-recognition-api'
branch: 'main'

# Skip specific checks
skip-check:
  - CKV_AWS_2 # Ensure no hardcoded secrets are present
  - CKV_AWS_18 # CloudTrail - managed at account level
  - CKV_AWS_20 # GuardDuty - managed at organization level
  - CKV_AWS_23 # Data stored in the EBS volume is encrypted
  - CKV_AWS_26 # Data stored in the SNS topic is encrypted
  - CKV_AWS_27 # Data stored in the SQS queue is encrypted
  - CKV_AWS_50 # S3 bucket versioning
  - CKV_AWS_53 # S3 bucket encryption
  - CKV_AWS_54 # S3 bucket public access
  - CKV_AWS_55 # S3 bucket logging
  - CKV_AWS_56 # S3 bucket versioning
  - CKV_AWS_65 # CloudTrail - managed at organization level
  - CKV_AWS_67 # CloudTrail - managed at account level
  - CKV_AWS_76 # VPC flow logs
  - CKV_AWS_91 # ALB access logging
  - CKV_AWS_115 # RDS instance backup
  - CKV_AWS_116 # RDS instance storage encryption
  - CKV_AWS_117 # RDS instance deletion protection
  - CKV_AWS_119 # RDS instance public accessibility
  - CKV_AWS_131 # Redshift cluster backup
  - CKV_AWS_150 # ElastiCache cluster backup
  - CKV_AWS_158 # Redshift cluster encryption
  - CKV_AWS_173 # ElastiCache cluster encryption
  - CKV_AWS_260 # RDS instance encryption
  - CKV_AWS_272 # Lambda function public accessibility
  - CKV_AWS_333 # IAM user with console access
  - CKV_AWS_338 # IAM policy allows full "*:*" administrative actions
  - CKV_AWS_355 # Security group with a rule that allows ingress from
  - CKV_AWS_382 # Unrestricted egress - required for ECS tasks to function properly

# Only run specific checks
check: []

# Skip specific frameworks
skip-framework: []
